apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-deployment
  namespace: default
  labels:
    app:  mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 2
  template:
    metadata:
      labels:
        app:  mongodb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mongodb
        image:  mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        ports:
        - containerPort:  27017

---
apiVersion: v1
kind: Service
metadata:
  name:  mongo-service
  namespace: default
spec:
  selector:
    app:  mongodb
 
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
   
        